server:
  port: "8080"

logging:
  level: "debug" # debug, info, warn, error
  # format: "json" # text, json
  # output: "stdout" # stdout, stderr, /path/to/logfile

performance:
  max_parallel_goroutines: 30
  rpc_call_timeout_seconds: 10 # ADDED: Timeout for individual RPC batch calls to nodes (in seconds)
  # http_client_timeout_seconds: 30